[Feat] 게시물 검색창 UI 구현 #9
Team-momo-front/momo-front pull request #10
Opened 2024-12-25 12:05 UTC by anony02

## 📌 관련 이슈
- close #9 

## 📝 변경 사항
- 게시물 검색창 UI 구현

## 🔍 테스트
- [ ] 테스트 코드 작성
- [ ] API 테스트
- [O] 로컬 테스트

## 📸 스크린샷
![image](https://github.com/user-attachments/assets/114b08cf-a62a-4867-a6a8-20aed0f0d2d8)

## ✅ 체크리스트
- [ ] main/develop 브랜치가 아닌 feature 브랜치에서 작성했나요?
- [ ] 코딩 컨벤션을 준수했나요?
- [ ] 불필요한 코드는 제거했나요?
- [ ] 주석은 충분히 작성했나요?
- [ ] 테스트는 완료했나요?

## 🙋‍♂️ 리뷰어에게
// 리뷰어가 집중해서 봐야 하는 부분
// 리뷰어에게 요청하고 싶은 사항

2024-12-25 16:21 UTC, wlals4264 requested changes

2024-12-25 16:21 UTC, wlals4264 commented on src/components/SearchBar/Select.tsx
> +const CustomDropdown = ({ selectedOption, setSelectedOption }: Props) => {
파일 이름과 컴포넌트 이름이 일치하도록 통일했으면 좋겠습니다.

2024-12-25 16:23 UTC, wlals4264 requested changes

2024-12-25 16:23 UTC, wlals4264 commented on src/components/SearchBar/Select.tsx
파일 이름과 컴포넌트 이름이 일치하도록 통일했으면 좋겠습니다.

2024-12-25 17:45 UTC, anony02 commented on src/components/SearchBar/Select.tsx
Select로 수정했습니다 [a9ee267](https://github.com/Team-momo-front/momo-front/pull/10/commits/a9ee267e431aea88ed0b09bc1adcf579df2c3e52)

2024-12-26 00:02 UTC, wlals4264 approved these changes

2024-12-26 00:03 UTC, wlals4264 approved these changes
고생하셨습니다!

2024-12-26 12:40 UTC, merged